//! Bounded lifecycle for Codex-hosted image generation results.
//!
//! The App Server item carries a Base64 string. We validate the decoded PNG
//! header and dimensions, retain only the bounded encoded result, and never
//! follow `savedPath` or write generated bytes into the ephemeral workspace.

use std::io::Cursor;

use base64::{Engine as _, engine::general_purpose::STANDARD};
use serde_json::{Value, json};

use crate::ProviderError;

pub(super) const MAX_GENERATED_IMAGE_BYTES: usize = 20 * 1024 * 1024;
const MAX_GENERATED_IMAGE_DIMENSION: u32 = 4096;
const MAX_GENERATED_IMAGE_PIXELS: u64 = 16_777_216;
const MAX_BASE64_CHARS: usize = MAX_GENERATED_IMAGE_BYTES.div_ceil(3) * 4;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct GeneratedImage {
    id: String,
    result: String,
    revised_prompt: Option<String>,
}

impl GeneratedImage {
    pub(super) fn from_completed_item(item: &Value) -> Result<Self, ProviderError> {
        if item.get("type").and_then(Value::as_str) != Some("imageGeneration") {
            return Err(ProviderError::Protocol(
                "Codex image result carried an unexpected item type".into(),
            ));
        }
        if item.get("status").and_then(Value::as_str) != Some("completed") {
            return Err(ProviderError::Protocol(
                "Codex image generation did not complete successfully".into(),
            ));
        }
        let id = item
            .get("id")
            .and_then(Value::as_str)
            .filter(|id| !id.is_empty())
            .ok_or_else(|| ProviderError::Protocol("imageGeneration omitted id".into()))?;
        let result = item
            .get("result")
            .and_then(Value::as_str)
            .filter(|result| !result.is_empty())
            .ok_or_else(|| ProviderError::Protocol("imageGeneration omitted result".into()))?;
        validate_png(result)?;
        let revised_prompt = item
            .get("revisedPrompt")
            .filter(|value| !value.is_null())
            .map(|value| {
                value.as_str().map(str::to_owned).ok_or_else(|| {
                    ProviderError::Protocol("imageGeneration revisedPrompt was not text".into())
                })
            })
            .transpose()?;
        Ok(Self {
            id: id.to_owned(),
            result: result.to_owned(),
            revised_prompt,
        })
    }

    pub(super) fn response_item(&self) -> Value {
        json!({
            "id": self.id,
            "type": "image_generation_call",
            "status": "completed",
            "result": self.result,
            "revised_prompt": self.revised_prompt,
        })
    }

    pub(super) fn id(&self) -> &str {
        &self.id
    }
}

fn validate_png(encoded: &str) -> Result<(), ProviderError> {
    if encoded.len() > MAX_BASE64_CHARS {
        return Err(ProviderError::Protocol(
            "Codex image result exceeded the encoded size limit".into(),
        ));
    }
    let decoded = STANDARD.decode(encoded).map_err(|_| {
        ProviderError::Protocol("Codex image result was not canonical Base64".into())
    })?;
    if decoded.is_empty() || decoded.len() > MAX_GENERATED_IMAGE_BYTES {
        return Err(ProviderError::Protocol(
            "Codex image result exceeded the decoded size limit".into(),
        ));
    }
    if image::guess_format(&decoded).ok() != Some(image::ImageFormat::Png) {
        return Err(ProviderError::Protocol(
            "Codex image result was not a PNG".into(),
        ));
    }
    let (width, height) =
        image::ImageReader::with_format(Cursor::new(&decoded), image::ImageFormat::Png)
            .into_dimensions()
            .map_err(|_| ProviderError::Protocol("Codex image PNG header was malformed".into()))?;
    let pixels = u64::from(width) * u64::from(height);
    if width == 0
        || height == 0
        || width > MAX_GENERATED_IMAGE_DIMENSION
        || height > MAX_GENERATED_IMAGE_DIMENSION
        || pixels > MAX_GENERATED_IMAGE_PIXELS
    {
        return Err(ProviderError::Protocol(
            "Codex image dimensions exceeded the safety limit".into(),
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn png_base64() -> String {
        let image = image::DynamicImage::new_rgb8(1, 1);
        let mut bytes = Cursor::new(Vec::new());
        image.write_to(&mut bytes, image::ImageFormat::Png).unwrap();
        STANDARD.encode(bytes.into_inner())
    }

    #[test]
    fn accepts_one_bounded_completed_png_without_following_saved_path() {
        let result = png_base64();
        let image = GeneratedImage::from_completed_item(&json!({
            "id": "image-1",
            "type": "imageGeneration",
            "status": "completed",
            "result": result,
            "revisedPrompt": "a small square",
            "savedPath": "/tmp/untrusted.png"
        }))
        .unwrap();
        assert_eq!(image.id(), "image-1");
        assert_eq!(
            image.response_item()["type"],
            Value::String("image_generation_call".into())
        );
    }

    #[test]
    fn rejects_non_png_and_incomplete_items_without_echoing_payloads() {
        for item in [
            json!({
                "id": "image-1",
                "type": "imageGeneration",
                "status": "completed",
                "result": STANDARD.encode(b"private prompt")
            }),
            json!({
                "id": "image-1",
                "type": "imageGeneration",
                "status": "inProgress",
                "result": png_base64()
            }),
        ] {
            let error = GeneratedImage::from_completed_item(&item).unwrap_err();
            assert!(!error.to_string().contains("private prompt"));
        }
    }
}
